### ISSUE TITLE
Návrh: Popis využitých technológií

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#10]
* konvertor, ak bude použitý
* knižnica na JSON, ak bude použitá

notorický známe veci písať netreba

**Comment by Chrumka16** [comment]
V zozname zatiaľ je:
•	CSS3 – umožňuje rozmiestnenie html objektov po stránke a úpravu celkového vizuálu stránky
•	HTML5 – umožňuje vytvoriť základnú kostru stránky
•	PHP – umožňuje spracovať údaje z formuláru a spustiť py skript
•	JSON – umožňuje, aby načítanie konfiguračných súborov vytvorilo objekt, s ktorým aplikácia dokáže pracovať
•	XLWT – umožňuje zápis do excelových súborov

Ak ešte niečo máte, napíšte to sem, prosím, aj s popisom.
