### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#11]
do 27. 11. 2017

Na Githube má byť dokument s testovacími scenármi, ktorý vznikne podľa Katalógu požiadaviek.

* každá požiadavka z katalógu musí byť kompletne pokrytá v nejakom testovacom scenári
* jeden scenár môže testovať aj viacero požiadaviek
* zoznam bodov, podla ktorých sa dá aplikáciu otestovať
* popis akcii a ich výsledkov (co sa môže stat ak sa niečo urobí)
* otestovať aj situácie, ktoré nie sú v KP (zabezpečenie robustnosti systému)

**Comment by Chrumka16** [comment]
[Testovacie scenáre.docx](https://github.com/TIS2018-FMFI/slabiky/files/2737020/Testovacie.scenare.docx)
