### ISSUE TITLE
Návrh: návrh používateľského rozhrania

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#13]
Návrh používateľského rozhrania:
- [x] - desktopová verzia webovej aplikácie
- [x] - mobilná verzia webovej aplikácie

**Comment by michalknor** [comment]
wireframe mobilnej verzie webovej aplikácie 
![mobil](https://user-images.githubusercontent.com/36670487/47964826-53e6db80-e03f-11e8-8887-cb68084ec026.png)

**Comment by Chrumka16** [comment]
Pridaj sem, prosím, aj tie počítačové rozhrania.

**Comment by michalknor** [comment]
![desktop2](https://user-images.githubusercontent.com/36670487/47982775-3febba00-e0d1-11e8-8e36-b6ac9bfd9e52.png)
![desktop1](https://user-images.githubusercontent.com/36670487/47982776-40845080-e0d1-11e8-9835-adce8523b2f8.png)

**Comment by Chrumka16** [comment]
Ďakujem. :)

**Comment by Chrumka16** [comment]
Návrh rozhrania bol schválený zadávateľom.
