### ISSUE TITLE
Návrh: modul - Backend webovej aplikácie

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#16]
- generovanie selectu jazykov na základe obsahu priečinku so súbormi jazykov
- v prípade vloženia textu to okna: uloží ho ako súbor s názvom vlozeny_txt_datum_cas.txt

**Comment by freivolt2** [comment]
Upravil som modul podla pripomienok.

**Comment by freivolt2** [comment]
Posielam finalny navrh backendu 
[Backend_navrh.docx](https://github.com/TIS2018-FMFI/slabiky/files/2595200/Backend_navrh.docx)
