### ISSUE TITLE
Návrh: modul - Spúšťací a ukončovací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#17]
- argumenty: jazyk, kódovanie, názov súboru
- načíta konfiguračný súbor (data) 
    > data = json.load(open('*.json', 'r'))
- zavolá Čítací modul
---
- čaká na ukončenie zapisovacích modulov
- upovedomí PHP

**Comment by freivolt2** [comment]
Upravil som modul podla pripomienok.

**Comment by freivolt2** [comment]
Posielam finalny navrh spustacieho modulu 
[Spustaci_navrh.docx](https://github.com/TIS2018-FMFI/slabiky/files/2595201/Spustaci_navrh.docx)
