### ISSUE TITLE
Návrh: modul - Upravovací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#19]
= Čistiaci modul
Thread 1

- argumenty: data, Slovo
- ak je slovo zlé (čiže obsahuj é 4), zahodí ho
- vymaže interpunkciu
- prerobí číslovanie v špecifických prípadoch
- ošetrí špeciálne prípady pre špeciálne znaky

**Comment by s-thora** [comment]
Spojený s [Čítacím modulom](https://drive.google.com/open?id=1Nvuyn_KISGFk0z-EN4z1tOe4XBraIRCeMmglUHGspws)

**Comment by toma-s** [comment]
[Upravovaci modul](https://docs.google.com/document/d/1Nvuyn_KISGFk0z-EN4z1tOe4XBraIRCeMmglUHGspws/edit?usp=sharing)

**Comment by toma-s** [comment]
[Uprava navrhu upravovacieho modulu](https://drive.google.com/open?id=1Nvuyn_KISGFk0z-EN4z1tOe4XBraIRCeMmglUHGspws)

**Comment by toma-s** [comment]
[Upravovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2570071/Upravovaci.modul.docx)

**Comment by toma-s** [comment]
[Upravovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2571384/Upravovaci.modul.docx)

**Comment by toma-s** [comment]
[Upravovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2586853/Upravovaci.modul.docx)
premenovala som výskyty názvov podtried triedy Word

**Comment by toma-s** [comment]
[Upravovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2610700/Upravovaci.modul.docx)
upraveny modul, podla zmien v navrhu po pridavani noveho zvukoveho modulu
