### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#2]
všetko hotovo najneskôr do 16. 10.

postupne odovzdáte tri samostatné výstupy: 

- [x] A. Podrobné poznámky zo stretnutia so zadávateľom - už potvrdené, resp. korigované zadávateľom

- [x] B. Neusporiadaný, nie nutne konzistentný, úplný a jednoznačný zoznam požiadaviek, ktoré tím vytvoril na základe poznámok

- [ ] C. Výsledný katalóg požiadaviek, ktorý odsúhlasil zadávateľ. Kým mal zadávateľ pripomienky, treba ich najskôr zohľadniť a ponúknuť mu na odsúhlasenie aktualizovanú, vylepšenú verziu.

**Comment by Chrumka16** [comment]
Naozaj si napísal, že sa volám Diabliková do Katalógu požiadaviek? Oprav to, prosím ťa, Palo... :D Volám sa Gablíková. Po oprave je Katalóg schválený zadávateľom a issue môže byť uzatvorené.

**Comment by Chrumka16** [comment]
Táto úloha je splnená. Uzatváram ju.
