### ISSUE TITLE
Návrh: modul - Slabikovací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#20]
Thread 2

- argumenty: dáta, Slovo
- podľa pravidiel rozslabikuje slovo

**Comment by Chrumka16** [comment]
[Slabikovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2545046/Slabikovaci.modul.docx)

**Comment by Chrumka16** [comment]
[Slabikovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2545082/Slabikovaci.modul.docx)
Opravila som chyby.

**Comment by Chrumka16** [comment]
[Slabikovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2546071/Slabikovaci.modul.docx)
Upravené podľa potrieb iných modulov.

**Comment by Chrumka16** [comment]
[Slabikovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2569579/Slabikovaci.modul.docx)
Upravené na OOP.

**Comment by Chrumka16** [comment]
[Slabikovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2591975/Slabikovaci.modul.docx)
Prerobené podľa nových názvov tried.

**Comment by Chrumka16** [comment]
[Slabikovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2613543/Slabikovaci.modul.docx)

Upravené na základe pridania Zvukového modulu
