### ISSUE TITLE
Návrh: modul - Zápis naslabikovaného textu

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#21]
Thread 4

- argumenty: pole slabík (zo Slabikovaceho modulu)
- ukladá polia do poľa a keď má dľžku n, zapíše to

**Comment by michalknor** [comment]
Pridané do [Návrhu](https://docs.google.com/document/d/1Nvuyn_KISGFk0z-EN4z1tOe4XBraIRCeMmglUHGspws/edit). Modul zároveň vykonáva aj to čo by mal robiť [modul - Zápis postupností dĺžok](https://github.com/TIS2018-FMFI/slabiky/issues/23).

**Comment by michalknor** [comment]
Premenované názvy tried: [zapis naslabikovaneho textu.docx](https://github.com/TIS2018-FMFI/slabiky/files/2593203/zapis.naslabikovaneho.textu.docx)
