### ISSUE TITLE
Návrh: modul - Počítací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#22]
- argumenty: pole slabík (zo Slabikovaceho modulu), dáta (zo Slabikovacieho modulu)
- pre každú slabiku zistí dĺžku a dá do dict dĺžok aj do poľa
- každú slabiku dá do dict výskytov

(už sa to nakopí)

**Comment by Chrumka16** [comment]
[Počítací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2546073/Pocitaci.modul.docx)
Návrh Počítacieho modulu.

**Comment by Chrumka16** [comment]
[Počítací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2569616/Pocitaci.modul.docx)
Upravené na OOP.

**Comment by Chrumka16** [comment]
[Počítací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2591977/Pocitaci.modul.docx)
Prerobené podľa nových názvov tried.
