### ISSUE TITLE
Návrh: modul -  Zápis postupností dĺžok

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#23]
Thread 5

- argumenty: pole dĺžok (z Počítacieho modulu)
ukladá polia do poľa a keď má dĺžku n, zapíše to

**Comment by michalknor** [comment]
Presunuté do [modulu - Zápis naslabikovaného textu](https://github.com/TIS2018-FMFI/slabiky/issues/21).

**Comment by Chrumka16** [comment]
Zatváram issue, keďže bolo zlúčené s iným.
