### ISSUE TITLE
Návrh: modul - Výsledkový modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#24]
- argumenty: dict (z Počítacieho modulu)
- zistí, aké dĺžky sa vyskytujú
- 1.: prejde dict dĺžok, ak má danú dĺžku tá slabika, tak početnosť +1
- 2.: prejde dict dĺžok, ak má danú dĺžku tá slabika, tak poèetnosť +dict výskytov

**Comment by pavelpetrovic** [comment]
ak vy vsetci tymto poznamkam rozumiete, tak je vsetko ok.
v dokumente to tam potom prosim napiste tak, aby som tomu tiez rozumel, vdaka

**Comment by michalknor** [comment]
Pridané do [Návrhu](https://docs.google.com/document/d/1Nvuyn_KISGFk0z-EN4z1tOe4XBraIRCeMmglUHGspws/edit).

**Comment by michalknor** [comment]
Update: [vysledkovy modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2593202/vysledkovy.modul.docx)
