### ISSUE TITLE
Návrh: modul - Zápis do excelu

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#25]
- argumenty: 1., 2. (z Výsledkového modulu), dict
- zapíše všetky 3 tabuľky

**Comment by pavelpetrovic** [comment]
dufam, ze vsetci clenovia timu rozumeju co je to "1., 2., dict", lebo ja z tohto nemam ani potuchy :-)

**Comment by michalknor** [comment]
Update: [zapis do excelu.docx](https://github.com/TIS2018-FMFI/slabiky/files/2593200/zapis.do.excelu.docx)
