### ISSUE TITLE
Testovacie scenáre - Frontend webovej aplikácie

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#29]

**Comment by freivolt2** [comment]
navrh frontend testovacich scenarov 
[testovacie_scenare.txt](https://github.com/TIS2018-FMFI/slabiky/files/2595216/testovacie_scenare.txt)

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
