### ISSUE TITLE
Návrh

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#3]
všetko hotovo najneskôr do 13.11.

návrh vytvoríte podľa dohody s cvičiacim podľa typu projektu, ktorý riešite. V každom prípade však musí obsahovať nasledujúce časti: 
- [x] A. podrobná špecifikácia vonkajších interfejsov - ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované
- [x] B. podrobný dátový model perzistentných údajov, formátov súborov, komunikačných protokolov.
- [x] C. návrh používateľského rozhrania (ak projekt má GUI) - nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom
- [x] D. Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

Výsledkom ma byt jeden dokument, ktorý:
* bude mat zrozumiteľnú pre tím štruktúru
* nie príliš detailný, ale aby podla toho sa dalo vyvinúť systém
* aby každý tím vedel programovať podla návrhu iného tímu

**Comment by pavelpetrovic** [comment]
bod D sa na stranke (v zmysle informacii na dnesnej prednaske) zmenil takto:

D. Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by Chrumka16** [comment]
Návrh verzia 2 (OOP návrh) je v julia-branch.

**Comment by toma-s** [comment]
Class Diagram: premenovať podtriedy triedy Word - @s-thora 
Sequence Diagram: spojiť dva diagramy pomocou alt - @s-thora 
Sequence Diagram: posunúť začiatok pre Backend - @s-thora 
Component Diagram: upraviť názvy - @s-thora 
slovný popis konfiguračného súboru - @Chrumka16 
premenovať výskyty názvov podtried triedy Word - @s-thora @Chrumka16  @michalknor 
WordRaw -> TextPunctuation
WordPhonotypes -> TextPhonotypes
WordSyllables -> SyllablesPhonotypes
WordLengths -> SyllablesLengths

**Comment by Chrumka16** [comment]
[Návrh.docx](https://github.com/TIS2018-FMFI/slabiky/files/2613548/Navrh.docx)
