### ISSUE TITLE
Testovacie scenáre - Spúšťací a ukončovací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#31]

**Comment by freivolt2** [comment]
[spustaci_testovacie_scenare.txt](https://github.com/TIS2018-FMFI/slabiky/files/2615532/spustaci_testovacie_scenare.txt)

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
