### ISSUE TITLE
Testovacie scenáre - Čitací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#32]

**Comment by toma-s** [comment]
Navrhujem nasledovnú štruktúru testov Čítacieho modulu pre rôzne testovacie vstupy poskytnuté zadávateľom.
Akcia: Modul dostane pole s prvkom typu Pipe pre výstup (pipe_out), adresu vstupného textu, jeho kódovanie, objekt triedy ConfigData.
Reakcia: Modul vloží do pipe_out objekt triedy TextPunctuation s atribútmi _text= [], _punct = [], alebo objekt triedy End.
Testovanie, či sa dá otvoriť vstupný súbor.
Testovanie, či objekt, vkladaný do pipe_out, zodpovedá očakávanému objektu.

**Comment by toma-s** [comment]
[Čítací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2659986/Citaci.modul.docx)

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
