### ISSUE TITLE
Testovacie scenáre - Upravovací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#33]

**Comment by toma-s** [comment]
Navrhujem nasledovnú štruktúru testov Upravovacieho modulu pre rôzne testovacie vstupy poskytnuté zadávateľom.
Akcia: Modul dostane pole s prvkami typu Pipe pre vstup (pipe_in) a výstup (pipe_out), objekt triedy ConfigData.
Reakcia: Modul vloží do pipe_out objekt triedy TextPhonotypes s atribútmi _text= [], _phonotypes = [], alebo objekt triedy End.
Testovanie, či objekt, vkladaný do pipe_out, zodpovedá očakávanému objektu.

**Comment by toma-s** [comment]
[Upravovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2659987/Upravovaci.modul.docx)

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
