### ISSUE TITLE
Testovacie scenáre - Slabikovací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#34]

**Comment by Chrumka16** [comment]
Navrhujem nasledovnú štruktúru testov Slabikovacieho modulu pre rôzne testovacie vstupny poskytnuté zadávateľom.
Akcia: Modul vyberie z pipe_in objekt s atribútmi _text = “”, _phonotypes = [].
Reakcia: Modul vloží do pipe_out objekt s atribútmi _syllables = [], _phonotypes = [].

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
