### ISSUE TITLE
Testovacie scenáre - Zápis naslabikovaného textu

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#35]

**Comment by michalknor** [comment]
Navrhujem nasledovnú štruktúru testov modulu "Zápis naslabikovaného textu" pre rôzne testovacie vstupy poskytnuté zadávateľom.
**Akcia**: 
Modul vyberie z pipe_in objekt s atribútmi _syllables = [], _phonotypes = []
**Reakcia**: 
Vytvoril sa súbor 'syllable_text.txt' a jeho obsah je: "".
Vytvoril sa súbor 'syllable_lengths_text.txt' a jeho obsah je: "".
Zmenil sa obsah súboru 'syllable_text.txt' a jeho obsah je: "".
Zmenil sa obsah súboru 'syllable_lengths_text.txt' a jeho obsah je: "".
_(posledné dva riadky sa môžu opakovať, ich počet je v závislosti od počtu slabík textu: (počet_slabík **div** 1000) + 1)_

Testuje sa či modul správne vytvoril súbory, pravidelne do nich zapisuje (každých 1000 hlások a na konci) a či skončí po prečítaní objektu triedy End.

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
