### ISSUE TITLE
Testovacie scenáre - Počítací modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#36]

**Comment by Chrumka16** [comment]
Navrhujem nasledovnú štruktúru testov Počítacieho modulu pre rôzne testovacie vstupny poskytnuté zadávateľom.
Akcia: Modul vyberie z pipe_in objekt s atribútmi _syllables = [], _phonotypes = [].
Reakcia: Modul vloží do pipe_out objekt s atribútmi _syllables = [], _lengths = [] a zavolá Výsledkový modul s agumentami map_len = {}, map_freq = {}, file_path (posunie argument, ktorý dostal pri vytvorení).

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
