### ISSUE TITLE
Testovacie scenáre - Výsledkový modul

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#38]

**Comment by michalknor** [comment]
Navrhujem nasledovnú štruktúru testov modulu 'Výsledkový modul' pre rôzne testovacie vstupy poskytnuté zadávateľom.

**Akcia**: 
Modul vyberie zo vstupných argumentov objekty map_len = {}, map_freq = {}
**Reakcia**: 
Modul zavolá modul [Zápis do excelu](https://github.com/TIS2018-FMFI/slabiky/issues/39) s argumentmi: map_len = {}, map_freq = {}, map_with_rep = {}, map_wout_rep = {}, file_path (posunie argument, ktorý dostal pri vytvorení).

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
