### ISSUE TITLE
Testovacie scenáre - Zápis do tabuliek

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#39]

**Comment by michalknor** [comment]
Navrhujem nasledovnú štruktúru testov modulu "Zápis do tabuliek" pre rôzne testovacie vstupy poskytnuté zadávateľom.

**Akcia**: 
Modul vyberie zo vstupných argumentov objekty map_len = {}, map_freq = {}, map_with_rep = {}, map_wout_rep = {}
**Reakcia**:
Vytvoril sa súbor 'syllables_multiplicity.xls' a jeho obsah je:
"".
Vytvoril sa súbor 'number_of_length_of_syllables_with_repetition.xls' a jeho obsah je:
"".
Vytvoril sa súbor 'number_of_length_of_syllables_without_repetition.xls' a jeho obsah je:
"".

**Comment by Chrumka16** [comment]
Sú zaradené v spoločnom súbore Testovacích scenárov.
