### ISSUE TITLE
Návrh: configuračné súbory

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#4]
Vytvorit konfiguracne subory pre pouzitije pri spracovani textu podla poskytnutych pravidel naslabikovania textu zadavatelom

**Comment by toma-s** [comment]
[Prva verzia configuracnych suborov](https://liveuniba-my.sharepoint.com/:f:/g/personal/savkova3_uniba_sk/EizCe9VE9ZZMpgkHs-Hnfp0B91jGCVojW9yHPmUCn_Zs1A?e=WNHS8K)

jazyky: chorvatčina, srbčina (lat, cyr), ukrajinčina, slovinčina

**Comment by pavelpetrovic** [comment]
pekne!
niekde sa tam vyskytuje pismeno "" - znamena to nieco specialne?
kdesi tam mate klucove slovo "correstonds to" - nemali ste na mysli "corresponds to" ?

**Comment by toma-s** [comment]
dakujem za upozornenia, uz som to upravila

**Comment by pavelpetrovic** [comment]
vyborne, nepridali by ste do toho formatu aj polozku "language-name" ? 
z mena suboru sa to neda celkom uhadnut.

**Comment by toma-s** [comment]
ano, pridala som aj pismo

**Comment by toma-s** [comment]
Pridala som konfiguracne subory do vetvy conf-tamara na github, [link](https://github.com/TIS2018-FMFI/slabiky/tree/conf-tamara/config).

Pridala som subory pre jazyky: hornoluzicka srbcina, rustina, a template pre pridavanie novych suborov.
Upravila som uz existujuce subory

**Comment by Chrumka16** [comment]
Super, tie dĺžky si spravila veľmi pekne a nezabudla si ani na digraphs, ďakujem. :)

**Comment by toma-s** [comment]
Pridala som konf. subory pre jazyky: bulgarcina, bielorustina
Upravila som konf. subory (podla novych suborov s pravidlami od zavatela) pre jazyky: rustina, ukrajincina, hornoluzicka srbcina
[Link](https://github.com/TIS2018-FMFI/slabiky/tree/conf-tamara/config)
