### ISSUE TITLE
Návrh: zmeny v návrhu počas implementácie

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#44]
Pridávajme sem zmeny oproti pôvodnému návrhu, ktoré nastanú počas implementácie, aby na konci prace na projekte sme upravili návrh podla týchto zmien naraz, a nie postupne

**Comment by toma-s** [comment]
Testovacie scenare - Čitací modul
[Čítací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2849327/Citaci.modul.docx)

**Comment by toma-s** [comment]
Testovacie scenare - Upravovací modul
[Upravovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2849443/Upravovaci.modul.docx)

**Comment by toma-s** [comment]
Navrh - Upravovaci modul
[Upravovací modul.docx](https://github.com/TIS2018-FMFI/slabiky/files/2849437/Upravovaci.modul.docx)

**Comment by michalknor** [comment]
Návrh - Zapisovací modul, výsledkový modul a tabuľkový modul

[misove moduly.docx](https://github.com/TIS2018-FMFI/slabiky/files/2850882/misove.moduly.docx)
