### ISSUE TITLE
Návrh: UML diagramy

### ISSUE THREAD

**Issue by toma-s** [TIS2018-FMFI/slabiky#9]
V navrhu maju byt

* UML Component diagram
    * jednotlive moduly budu komponentami UML Komponentného diagramu
    * popísane rozhrania komponentov
    * co komponenty majú na starosti
    * API alebo verejne metódy, do ktorých dosahuje funkcionalita časti

* UML Class diagram
    * je najlepšie vygenerovať automaticky
    * Python IDE majú nástroje\pluginy na generovanie UML Class diagramov

* text, popisujúci každý z tých komponentov
    * nie príliš detailne, ale dostatočne, aby podla toho sa dalo vyvinúť systém

* UML State alebo UML Sequence diagram (aspoň jeden z dvojice)

**Comment by toma-s** [comment]
Class diagram
![class diagram](https://user-images.githubusercontent.com/19805197/48320224-46b98600-e617-11e8-80a2-603a5421b534.png)

Component diagram
![component diagram](https://user-images.githubusercontent.com/19805197/48320225-47521c80-e617-11e8-9aad-6f2e41ab4d1a.jpg)

Sequence diagram
![sequence diagram](https://user-images.githubusercontent.com/19805197/48320226-47521c80-e617-11e8-8bb4-bd7bd6653d36.jpg)

**Comment by toma-s** [comment]
Class diagram

![class diagram](https://user-images.githubusercontent.com/19805197/48337595-a9d10a00-e663-11e8-8ee8-96dec14dd3bf.png)

**Comment by toma-s** [comment]
Class Diagram
![class diagram](https://user-images.githubusercontent.com/19805197/48662850-4f331600-ea88-11e8-9e1b-bf29d610889b.png)

Component Diagram
![component diagram](https://user-images.githubusercontent.com/19805197/48662641-22313400-ea85-11e8-8046-ebeaed6c24cc.jpg)

Sequence Diagram
![sequence diagram](https://user-images.githubusercontent.com/19805197/48662645-28271500-ea85-11e8-9d1c-758c6a944074.jpg)

**Comment by Chrumka16** [comment]
Ďakujem za opravy. Zatváram issue. :)

**Comment by toma-s** [comment]
Aktualizovane diagramy po pridani noveho Zvukoveho modulu

Class Diagram
![class diagram](https://user-images.githubusercontent.com/19805197/48967989-1693bf00-efe9-11e8-903f-40eb40917526.png)

Component Diagram
![component diagram](https://user-images.githubusercontent.com/19805197/48967990-1693bf00-efe9-11e8-9a0b-74307fe52c84.png)

Sequence Diagram
![sequence diagram](https://user-images.githubusercontent.com/19805197/48967991-1693bf00-efe9-11e8-8844-a3b4d2a427c3.png)

**Comment by toma-s** [comment]
Upraveny Class Diagram podla aktualnej struktury konfiguracnych suborov
![class diagram](https://user-images.githubusercontent.com/19805197/49103861-c6cd2600-f27c-11e8-959d-b2a3cc04325d.png)
